# Generated by Django 3.2.14 on 2022-08-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, default='imgagepath', help_text='图片路径', upload_to='image/%Y%m%d', verbose_name='图片')),
                ('create_dt', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('modify_dt', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('status', models.CharField(choices=[('P', '公开'), ('H', '隐藏')], default='P', help_text='是否可见', max_length=1, verbose_name='是否可见')),
            ],
            options={
                'verbose_name': '图像库',
                'verbose_name_plural': '图像库',
                'db_table': 'imagefile',
            },
        ),
    ]
