# Generated by Django 3.2.14 on 2022-08-22 01:12

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.IntegerField(help_text='用户id', primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(help_text='用户名', max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(help_text='用户密码', max_length=128, verbose_name='密码')),
                ('email', models.EmailField(help_text='用户邮箱', max_length=254, unique=True, verbose_name='邮箱')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'auser',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Faceidcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceimg', models.ImageField(blank=True, default='', help_text='刷脸图片', upload_to='faceidcard/%Y%m%d', verbose_name='刷脸图片')),
                ('chin', models.CharField(default=[], help_text='下巴', max_length=128, verbose_name='下巴')),
                ('left_eyebrow', models.CharField(default=[], help_text='左眉', max_length=128, verbose_name='左眉')),
                ('right_eyebrow', models.CharField(default=[], help_text='右眉', max_length=128, verbose_name='右眉')),
                ('nose_bridge', models.CharField(default=[], help_text='鼻桥', max_length=128, verbose_name='鼻桥')),
                ('nose_tip', models.CharField(default=[], help_text='鼻尖', max_length=128, verbose_name='鼻尖')),
                ('left_eye', models.CharField(default=[], help_text='左眼', max_length=128, verbose_name='左眼')),
                ('right_eye', models.CharField(default=[], help_text='右眼', max_length=128, verbose_name='右眼')),
                ('top_lip', models.CharField(default=[], help_text='上唇', max_length=128, verbose_name='上唇')),
                ('bottom_lip', models.CharField(default=[], help_text='下唇', max_length=128, verbose_name='下唇')),
                ('face_encoding', models.CharField(default=[], help_text='128位人脸编码', max_length=128, verbose_name='刷脸编码')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faceidcard_user', to=settings.AUTH_USER_MODEL, verbose_name='刷脸用户')),
            ],
            options={
                'verbose_name': '用户人脸数据',
                'verbose_name_plural': '用户人脸数据',
                'db_table': 'faceidcard',
            },
        ),
    ]
